// Visual-regression goldens (D3) via alchemist CI goldens.
//
// The committed PNGs are Linux-generated by the `golden-update` workflow; the
// diff threshold in test/flutter_test_config.dart absorbs cross-architecture
// anti-aliasing, so these also run locally. Escape hatch there if a host ever
// diverges past it.
//
// Regenerate after an intentional visual change with the `golden-update`
// workflow (`gh workflow run golden-update.yml --ref <branch>`), then commit the
// `ci-goldens` artifact — never with a local `flutter test --update-goldens`.
//
// NOT covered here, deliberately: PulseSnackBar and PulseBottomSheet. Both are
// overlay/route-driven, so snapshotting them means pumping a host widget that
// shows them and then living with the auto-dismiss timer and entrance route
// still in flight at teardown — flaky infrastructure guarding widgets whose
// colours and structure are already asserted directly (pulse_snack_bar_test.dart
// and pulse_bottom_sheet_test.dart). Naming the gap beats a test that fails for
// reasons unrelated to what it claims to check.

import 'package:alchemist/alchemist.dart';
import 'package:flutter/material.dart';
import 'package:pulse_theme/pulse_theme.dart';

void main() {
  // The full variant × tone × size matrix. Iterating `.values` on both enums
  // means a new variant or tone cannot be added without its goldens appearing.
  goldenTest(
    'PulseButton — variants × tones × sizes',
    fileName: 'pulse_button',
    builder:
        () => GoldenTestGroup(
          columns: 3,
          children: [
            for (final variant in PulseButtonVariant.values)
              for (final tone in PulseButtonTone.values)
                for (final size in PulseButtonSize.values)
                  GoldenTestScenario(
                    name: '${variant.name}/${tone.name}/${size.name}',
                    child: PulseButton(
                      variant: variant,
                      tone: tone,
                      size: size,
                      onPressed: () {},
                      child: const Text('ボタン'),
                    ),
                  ),
          ],
        ),
  );

  // `isLoading` is a *layout* contract as much as a visual one: the label stays
  // laid out (invisible) behind the spinner so the button keeps the width it had
  // before submit. Each variant is rendered twice with the identical label —
  // idle next to loading — so a regression that shrinks the busy button to the
  // spinner's size shows up as two boxes of different widths in one row.
  goldenTest(
    'PulseButton — isLoading (width is preserved)',
    fileName: 'pulse_button_loading',
    // The spinner never settles, so alchemist's default `onlyPumpAndSettle`
    // would time out. Pump a single frame at a fixed offset instead: fake-async
    // time is deterministic, so every run captures the same arc. 400ms is past
    // the 200ms button/theme implicit animations (everything else is at rest)
    // and lands mid-sweep of the 1333ms indeterminate cycle — at t=0 the arc is
    // zero-length and the spinner would be invisible in the snapshot.
    pumpBeforeTest: pumpNTimes(1, const Duration(milliseconds: 400)),
    builder:
        () => GoldenTestGroup(
          // Two columns => one combination per row, idle | loading side by side.
          columns: 2,
          children: [
            for (final variant in PulseButtonVariant.values)
              for (final tone in PulseButtonTone.values)
                for (final isLoading in [false, true])
                  GoldenTestScenario(
                    name:
                        '${variant.name}/${tone.name}/'
                        '${isLoading ? 'loading' : 'idle'}',
                    child: PulseButton(
                      variant: variant,
                      tone: tone,
                      onPressed: () {},
                      isLoading: isLoading,
                      loadingSemanticsLabel: 'Submitting',
                      child: const Text('Submit'),
                    ),
                  ),
          ],
        ),
  );

  // Edge values as well as a mid value: 0.0 and 1.0 are where an off-by-one in
  // the fill geometry shows up, and the indeterminate mode has no `value` at
  // all, so it exercises a different paint path entirely.
  goldenTest(
    'PulseProgressIndicator — determinate edges + indeterminate',
    fileName: 'pulse_progress',
    // The indeterminate sweep never settles, so pump a single frame at a fixed
    // offset instead (same technique as the loading-button golden).
    pumpBeforeTest: pumpNTimes(1, const Duration(milliseconds: 400)),
    builder:
        () => GoldenTestGroup(
          columns: 1,
          children: [
            for (final (name, value) in <(String, double?)>[
              ('0%', 0),
              ('65%', 0.65),
              ('100%', 1),
              ('indeterminate', null),
            ])
              GoldenTestScenario(
                name: name,
                child: SizedBox(
                  width: 240,
                  child: PulseProgressIndicator(value: value),
                ),
              ),
          ],
        ),
  );

  goldenTest(
    'PulseLoadingState — three variants',
    fileName: 'pulse_loading',
    // A spinner never settles; 400ms lands mid-sweep of the 1333ms cycle (at
    // t=0 the arc is zero-length and would be invisible in the snapshot).
    pumpBeforeTest: pumpNTimes(1, const Duration(milliseconds: 400)),
    builder:
        () => GoldenTestGroup(
          columns: 3,
          children: [
            GoldenTestScenario(
              name: 'default (40)',
              child: const SizedBox(
                width: 200,
                height: 160,
                child: PulseLoadingState(message: '読み込み中'),
              ),
            ),
            GoldenTestScenario(
              name: 'compact (24)',
              child: const SizedBox(
                width: 200,
                height: 160,
                child: PulseLoadingState.compact(message: '同期中'),
              ),
            ),
            GoldenTestScenario(
              name: 'inline (16)',
              child: const PulseLoadingState.inline(),
            ),
          ],
        ),
  );

  goldenTest(
    'PulseTabBar — light and dark',
    fileName: 'pulse_tab_bar',
    builder:
        () => GoldenTestGroup(
          columns: 1,
          children: [
            GoldenTestScenario(
              name: 'light',
              child: const SizedBox(width: 360, child: _Tabs()),
            ),
            GoldenTestScenario(
              name: 'dark',
              child: onDark(const SizedBox(width: 360, child: _Tabs())),
            ),
          ],
        ),
  );

  // Dark mode had NO visual coverage at all until 0.7.0, and dark is where
  // every colour bug this package has shipped actually lived: the white-on-red
  // `onError` pair (0.5.0), the invisible `inversePrimary` and the snack bar
  // that never flipped its success/warning tokens (0.6.0), and a section-card
  // shadow that stayed at 5% black on a surface the same colour as the
  // scaffold behind it.
  //
  // Sizes are not repeated here: the size axis is padding and font-size
  // constants, which do not vary by mode, and it is already covered in light.
  goldenTest(
    'PulseButton — dark, every variant × tone',
    fileName: 'pulse_button_dark',
    builder:
        () => GoldenTestGroup(
          columns: 2,
          children: [
            for (final variant in PulseButtonVariant.values)
              for (final tone in PulseButtonTone.values)
                GoldenTestScenario(
                  name: '${variant.name}/${tone.name}',
                  child: onDark(
                    PulseButton(
                      variant: variant,
                      tone: tone,
                      onPressed: () {},
                      child: const Text('ボタン'),
                    ),
                  ),
                ),
          ],
        ),
  );

  goldenTest(
    'PULSE states — dark (empty / error / section card)',
    fileName: 'pulse_states_dark',
    builder:
        () => GoldenTestGroup(
          columns: 1,
          children: [
            GoldenTestScenario(
              name: 'empty',
              child: onDark(
                const SizedBox(
                  width: 320,
                  height: 380,
                  child: PulseEmptyState(
                    icon: Icon(Icons.inbox),
                    title: 'まだ記録がありません',
                    description: '最初のワークアウトを記録してみましょう',
                  ),
                ),
              ),
            ),
            GoldenTestScenario(
              name: 'error',
              child: onDark(
                const SizedBox(
                  width: 320,
                  height: 320,
                  child: PulseErrorState(
                    title: '読み込みに失敗しました',
                    message: '時間をおいて再試行してください',
                  ),
                ),
              ),
            ),
            GoldenTestScenario(
              name: 'section-card',
              child: onDark(
                const SizedBox(
                  width: 320,
                  child: PulseSectionCard(
                    title: '今週のトレーニング',
                    child: Text('内容がここに入ります'),
                  ),
                ),
              ),
            ),
          ],
        ),
  );

  goldenTest(
    'PULSE states (empty / error / section card)',
    fileName: 'pulse_states',
    builder:
        () => GoldenTestGroup(
          columns: 1,
          children: [
            GoldenTestScenario(
              name: 'empty',
              child: const SizedBox(
                width: 320,
                height: 380,
                child: PulseEmptyState(
                  icon: Icon(Icons.inbox),
                  title: 'まだ記録がありません',
                  description: '最初のワークアウトを記録してみましょう',
                ),
              ),
            ),
            GoldenTestScenario(
              name: 'error',
              child: const SizedBox(
                width: 320,
                height: 320,
                child: PulseErrorState(
                  title: '読み込みに失敗しました',
                  message: '時間をおいて再試行してください',
                ),
              ),
            ),
            GoldenTestScenario(
              name: 'section-card',
              child: const SizedBox(
                width: 320,
                child: PulseSectionCard(
                  title: '今週のトレーニング',
                  child: Text('内容がここに入ります'),
                ),
              ),
            ),
          ],
        ),
  );
}

/// Renders [child] under [PulseTheme.dark] on the dark surface.
///
/// Alchemist applies one theme per config, so a dark scenario re-themes its own
/// subtree. The [ColoredBox] is load-bearing: without the dark surface behind
/// it, dark-mode content would be snapshotted against alchemist's own light
/// backdrop and a contrast regression could hide in plain sight.
Widget onDark(Widget child) {
  final theme = PulseTheme.dark();
  return Theme(
    data: theme,
    child: ColoredBox(
      color: theme.colorScheme.surface,
      child: Padding(
        padding: const EdgeInsets.all(PulseSpacing.md),
        child: child,
      ),
    ),
  );
}

/// A three-tab [PulseTabBar] with the controller it needs.
class _Tabs extends StatelessWidget {
  const _Tabs();

  @override
  Widget build(BuildContext context) {
    return const DefaultTabController(
      length: 3,
      child: PulseTabBar(
        tabs: [Tab(text: '概要'), Tab(text: '履歴'), Tab(text: '設定')],
      ),
    );
  }
}
